### ISSUE TITLE
skip login official server

### ISSUE THREAD

**Issue by wcjqwq** [Melledy/LunarCore#11]
skip login official server
![image](https://github.com/Melledy/LunarCore/assets/92256031/5c941b11-8ca5-4e9e-9ff7-858681b14b32)
    "assetBundleUrl": "https://autopatchcn.bhsr.com/asb/V1.5Live/output_6009646_316df06a76",
    "exResourceUrl": "https://autopatchcn.bhsr.com/design_data/V1.5Live/output_6009646_316df06a76",
    "luaUrl": "https://autopatchcn.bhsr.com/lua/V1.5Live/output_5959621_b94efa50f5",
    "ifixUrl": "https://autopatchcn.bhsr.com/ifix/V1.5Live/output_6009646_316df06a76"
By the way, what are the six unknowns on the gateway?

**Comment by Hiro420** [comment]
Not a good idea since we will need to update the cur every single time.
It's better to download them from official servers and keep the download links optional in case you can't.
