### ISSUE TITLE
StarRailData repo got DMCA-ed

### ISSUE THREAD

**Issue by Bugstudios** [Melledy/LunarCore#110]
as title said, are there any new repo?

**Comment by yuko1101** [comment]
https://gitlab.com/Dimbreath/turnbasedgamedata

**Comment by Saobby** [comment]
please see https://gitlab.com/Dimbreath/turnbasedgamedata







---- zhx201933 ***@***.***> 在 周二, 05 11月 2024 16:32:04 +0800 写到：---





as title said, are there any new repo?

**Comment by MistakingManx** [comment]
~~This resource doesn't have "/Config/LevelOutput/Floor", which LunarCore says it needs.~~
https://gitlab.com/Melledy/LunarCore-Configs
