### ISSUE TITLE
The frame rate of the newly added floating screen announcement at the top is a bit low | 新添加的这个顶部飘屏公告有点掉帧

### ISSUE THREAD

**Issue by Ken-Parker** [Melledy/LunarCore#19]
https://github.com/Melledy/LunarCore/assets/33827973/1209d030-8b3f-456c-af29-510da4a9b96d

i knew it can be closed...只是卡卡的，有点影响观感...不算什么大问题

**Comment by Hiro420** [comment]
its speed and framerate is 100% client-side, we cant change that
