### ISSUE TITLE
Can i change my game data from the database?

### ISSUE THREAD

**Issue by xiele88787** [Melledy/LunarCore#22]
i have already a game server on my localhost,i wonder where the game data store at?and how can i edit it?

**Comment by xiele88787** [comment]
if can,plz point out the path

**Comment by xiele88787** [comment]
thx，can i use it on Android?

**Comment by Hiro420** [comment]
> can i change the gecha chance?and the character ability number?

gacha chance is only change-able from the server source code, not database.
ability number is something you can refill using /refill command
