### ISSUE TITLE
Can you tell me how to make LunarCore run on Honkai: Star Rail on Android?

### ISSUE THREAD

**Issue by zmxlsss666** [Melledy/LunarCore#30]
Can you tell me how to make LunarCore run on Honkai: Star Rail on Android?

**Comment by Whirity404** [comment]
> > Can you tell me how to make LunarCore run on Honkai: Star Rail on Android?
> 
> https://github.com/baiqilingnai/Xueby-StarRailSever-Android-Sever

Oops, this link is broken, it can't download Android one-click package now, is there any other way to run it on Android?
