### ISSUE TITLE
Impact of Hash Value 5ed1941 on New Account Registrations: Error 1001_1|哈希值5ed1941对新账号注册的影响：Error 1001_1

### ISSUE THREAD

**Issue by HongchengQ** [Melledy/LunarCore#31]
The submission with the hash value 5ed1941 is causing Error 1001_1 for newly registered accounts (previously registered accounts are unaffected).
哈希值5ed1941的提交导致新注册的账号Error 1001_1(原来已经注册过的账号不受影响)
<img width="842" alt="屏幕截图 2023-12-28 184034" src="https://github.com/Melledy/LunarCore/assets/121159914/148f9c39-3138-4e67-829c-3de1f66baa9d">

**Comment by Melledy** [comment]
Should be fixed in 490a34c
