### ISSUE TITLE
Can I set a password for the LunarCore database？

### ISSUE THREAD

**Issue by Yizuko** [Melledy/LunarCore#39]
Just today, my LunarCore database was hacked (not the built-in database) and all my data was lost, I hope someone can tell me how to modify the source code to set the password for LC's MongoDB, thank you

**Comment by KingRainbow44** [comment]
...this is a new one

1. is your database on a public server?
2. you don't need to modify source code at all, add a password to your mongodb instance and update the mongo URI in the config
