### ISSUE TITLE
Main character can't be set to the female character

### ISSUE THREAD

**Issue by wangwenx190** [Melledy/LunarCore#45]
LuncarCore version: 7cf67f6149e4d92631317264375100d85e13c371
Game version: 2.0.0

Currently LunarCore use the male character (ID: 8001) as the main character, however, when I changed the ID from 8001 to 8002 to try to use the female character, the game can't finish loading, it will stuck at the loading phase. The /gender command also doesn't work.

**Comment by Haruko-kun** [comment]
Don't change the default characters in the json file, it will definitely cause errors in your game. As for the gender command, after using it, you need to restart the game

**Comment by wangwenx190** [comment]
No I didn't touch any json file, in fact, I just changed the following line:

https://github.com/Melledy/LunarCore/blob/f82fd023a8e8a39ea4829223a6501901a83d5c41/src/main/java/emu/lunarcore/GameConstants.java#L17

After many times of trying, it seems only 8001 works well. All other ids will prevent the game from normally loading.

**Comment by wangwenx190** [comment]
And if I keep waiting, Windows (not the game) will crash and then my PC was forcely restarted.

**Comment by wangwenx190** [comment]
Anyway, restart the game indeed fixed the /gender command. Thanks!
