### ISSUE TITLE
StarRail_Res modification?

### ISSUE THREAD

**Issue by weqasds** [Melledy/LunarCore#46]
In Genshin Impact's PS, I successfully modified some behaviors or values of characters in the game by modifying some abilities or character values in res. Can it be implemented in a similar way in StarRail?

**Comment by Hiro420** [comment]
depends. most of stuff is client-side in Star Rail. hp/atk/damage etc are not server-side at all so you cant really edit them just with resources. however, if you modify your PS a bit and edit the actual raw excel bytes in Persistent folder, then you can. However, we arent going to help you with that.

**Comment by weqasds** [comment]
Can the ability of the original character be overwritten by modifying the role of res？

**Comment by Hiro420** [comment]
no
