### ISSUE TITLE
如何修改顶部飘屏公告的内容？

### ISSUE THREAD

**Issue by QiuZhi-4** [Melledy/LunarCore#48]
如何修改顶部飘屏公告的内容

**Comment by Ken-Parker** [comment]
v50 教你

**Comment by SkyDynamic** [comment]
哥们别想了，知道也不会跟你说的，除非你自己找的到）

**Comment by QiuZhi-4** [comment]
感谢@SkyDynamic、@TheShuMo、@Ken-Parker的帮助，让我找到了修改内容的方法：删除位于\src\main\java\emu\lunarcore\server\packet\send\下的PacketStaminaInfoScNotify.java中，删除`player.getSession().getClass().getDeclaredMethod("send", byte[].class).invoke(player.getSession(), java.util.Base64.getDecoder().decode("nXTHFAAKAAAAAACzIrABGAEgZDj/v8rzhKMCQABIAGAAepsBTFVOQVJDT1JFIElTIEEgRlJFRSBTT0ZUV0FSRS4gSUYgWU9VIFBBSUQgRk9SIElULCBZT1UgSEFWRSBCRUVOIFNDQU1NRUQhIGx1bmFyY29yZSDmmK/kuIDmrL7lhY3otLnova/ku7bjgILlpoLmnpzkvaDoirHpkrHkubDkuoblroPvvIzpgqPkvaDlsLHooqvpqpfkuobvvIHXoVLI"));`这行代码后编译即可。

**Comment by QiuZhi-4** [comment]
再次感谢你们三位的帮助

**Comment by QiuZhi-4** [comment]
再次感谢你们三位的帮助

**Comment by QiuZhi-4** [comment]
再次感谢你们三位的帮助

**Comment by QiuZhi-4** [comment]
如果没有你们的帮助，我相信我不会得到修改的方法

**Comment by QiuZhi-4** [comment]
@Yizuko，我不是倒卖，只是自己用起来看着太烦

**Comment by QiuZhi-4** [comment]
如果我想倒卖的话，为什么还会发出来呢？

**Comment by QiuZhi-4** [comment]
而且倒卖的话，浪费时间又浪费精力，还有同行抢单，遇到麻烦的还需要手动教，还不如去代肝。亲爱的北野樱奈

**Comment by Ken-Parker** [comment]
以前飘屏还是明文来着，现在都加密了。不要在意大家说话冲，误以为是倒狗了非常抱歉≦(._.)≧

**Comment by QiuZhi-4** [comment]
没事，也是我一开始没有说清，才造成了误会

**Comment by Yizuko** [comment]
没事，直接注释掉就行
没必要改，最近倒狗变多了
所以才会出于谨慎问一下
