### ISSUE TITLE
Add support to hkrpg_cn biz

### ISSUE THREAD

**Issue by ZianTT** [Melledy/LunarCore#61]
the game in china use hkrpg_cn as the game_biz. Can you handle the request to /hkrpg_cn/* request? Thanks!

**Comment by ZianTT** [comment]
ok有用3x

**Comment by ZianTT** [comment]
hmmm还是有点问题，依然会404，应该还是发到了/hkrpg_cn上，前面应该是缓存或者什么的，并没有什么效果

**Comment by ZianTT** [comment]
> lc的服务端是可以用于cnAndioid的 我自己亲身试过 可能是你的apk没有修改正确 你可以使用这个工具来生成apk需要的文件https://github.com/BanxiaServer/HSR_Bytes-Tool.git

em我是win版，登录时会显示miHoYo标然后请求都发到hkrpg_cn然后404…

**Comment by HongchengQ** [comment]
应该是你的代理软件有什么问题 可以试试https://github.com/Grasscutters/Cultivation

**Comment by ZianTT** [comment]
> 应该是你的代理软件有什么问题 可以试试https://github.com/Grasscutters/Cultivation

好的
