### ISSUE TITLE
获取服务器分发错误

### ISSUE THREAD

**Issue by QSlotus** [Melledy/LunarCore#73]
我使用最新的LunarCore的actions部署了sr的服务器，在本地连接的时候一切正常（连接地址为localhost:port），能够正常进入与游玩。但是当我将其整个打包放到我的VPS中时，我无法进入服务器，显示“获取服务器分发错误”
我已将http端口与gameserver端口放行并且开启了端口映射（内外网端口一致）
启动游戏客户端后，我能看到我已经用私服的账号登录，但是登录之后马上弹出错误。
![image](https://github.com/Melledy/LunarCore/assets/109905194/6892daa0-e444-4758-a777-65e7c06204c9)
![image](https://github.com/Melledy/LunarCore/assets/109905194/86ac4ce1-f97a-40f9-ac5b-eef89950546a)

系统环境：
- Ubuntu 22.04
- JDK 17
- 未安装MongoDB（之前在本地测试时也未安装MongoDB但是能够成功进入

我在discord中找到了这一条建议：
![image](https://github.com/Melledy/LunarCore/assets/109905194/113c4265-3d3c-4d34-82df-271423a28f03)
但是我在浏览器中访问该地址时正常返回了数据
![dc5bcd47874e391c67cbcaffa21f5609](https://github.com/Melledy/LunarCore/assets/109905194/d9d8db50-a682-4500-a991-60a78bab7cbe)

这是我的LunarCore服务端的运行日志：

```
[20:19:01] [INFO] Starting Lunar Core 1.2.0
[20:19:01] [INFO] Git hash: d87f04f (2024-05-11 19:47:46)
[20:19:01] [INFO] Game version: 2.2.0
[20:19:02] [INFO] Loaded 378 AvatarPromotionExcels.
[20:19:02] [INFO] Loaded 324 AvatarRankExcels.
[20:19:02] [INFO] Loaded 700 EquipmentPromotionExcels.
[20:19:02] [INFO] Loaded 132 ChallengeTargetExcels.
[20:19:02] [INFO] Loaded 615 RogueMapExcels.
[20:19:02] [INFO] Loaded 161 NpcMonsterExcels.
[20:19:02] [INFO] Loaded 109 BackGroundMusicExcels.
[20:19:02] [INFO] Loaded 1131 MonsterExcels.
[20:19:02] [INFO] Loaded 42 RogueTalentExcels.
[20:19:02] [INFO] Loaded 704 RogueRoomExcels.
[20:19:02] [INFO] Loaded 4078 RewardExcels.
[20:19:02] [INFO] Loaded 20 RogueNousSubStoryExcels.
[20:19:02] [INFO] Loaded 399 ChallengeExcels.
[20:19:02] [INFO] Loaded 9 SummonUnitExcels.
[20:19:02] [INFO] Loaded 771 PropExcels.
[20:19:02] [INFO] Loaded 252 CocoonExcels.
[20:19:02] [INFO] Loaded 1181 RogueMonsterExcels.
[20:19:02] [INFO] Loaded 240 EquipmentExpTypeExcels.
[20:19:02] [INFO] Loaded 16 RogueDLCAreaExcels.
[20:19:02] [INFO] Loaded 766 NpcExcels.
[20:19:02] [INFO] Loaded 64 RelicExpTypeExcels.
[20:19:02] [INFO] Loaded 184 BattleEventDataExcels.
[20:19:02] [INFO] Loaded 60 ShopExcels.
[20:19:02] [INFO] Loaded 42 ChallengeGroupExcels.
[20:19:02] [INFO] Loaded 80 TextJoinExcels.
[20:19:02] [INFO] Loaded 48 RelicSubAffixExcels.
[20:19:02] [INFO] Loaded 412 MapEntranceExcels.
[20:19:02] [INFO] Loaded 171 MazePlaneExcels.
[20:19:02] [INFO] Loaded 2311 QuestExcels.
[20:19:02] [INFO] Loaded 186 ItemUseExcels.
[20:19:02] [INFO] Loaded 12 RogueNousDiceBranchExcels.
[20:19:02] [INFO] Loaded 117 RelicMainAffixExcels.
[20:19:02] [INFO] Loaded 112 ActivityPanelExcels.
[20:19:02] [INFO] Loaded 200 ExpTypeExcels.
[20:19:02] [INFO] Loaded 32 RelicSetExcels.
[20:19:02] [INFO] Loaded 17 RogueBonusExcels.
[20:19:02] [INFO] Loaded 1043 MazeBuffExcels.
[20:19:02] [INFO] Loaded 8 RogueNousMainStoryExcels.
[20:19:02] [INFO] Loaded 260 RogueNPCExcels.
[20:19:02] [INFO] Loaded 201 InteractExcels.
[20:19:02] [INFO] Loaded 54 AvatarExcels.
[20:19:03] [INFO] Loaded 17963 StageExcels.
[20:19:03] [INFO] Loaded 6 HeroExcels.
[20:19:03] [INFO] Loaded 78 RogueManagerExcels.
[20:19:03] [INFO] Loaded 70 PlayerLevelExcels.
[20:19:03] [INFO] Loaded 39 PlayerIconExcels.
[20:19:03] [INFO] Loaded 9 RogueAeonExcels.
[20:19:03] [INFO] Loaded 250 RogueMiracleExcels.
[20:19:03] [INFO] Loaded 2925 ItemExcels.
[20:19:03] [INFO] Loaded 225 ItemComposeExcels.
[20:19:03] [INFO] Loaded 1343 DialogueEventExcels.
[20:19:03] [INFO] Loaded 100 EquipmentExcels.
[20:19:03] [INFO] Loaded 484 RogueBuffExcels.
[20:19:03] [INFO] Loaded 925 MappingInfoExcels.
[20:19:03] [INFO] Loaded 45 ChallengeRewardExcels.
[20:19:03] [INFO] Loaded 1750 MonsterDropExcels.
[20:19:03] [INFO] Loaded 3 EquipmentExpItemExcels.
[20:19:03] [INFO] Loaded 546 RogueBuffGroupExcels.
[20:19:03] [INFO] Loaded 24 ChallengeStoryExtraExcels.
[20:19:03] [INFO] Loaded 451 ShopGoodsExcels.
[20:19:03] [INFO] Loaded 6 ChatBubbleExcels.
[20:19:03] [INFO] Loaded 2700 AvatarSkillTreeExcels.
[20:19:03] [INFO] Loaded 3 AvatarExpItemExcels.
[20:19:03] [INFO] Loaded 406 RelicExcels.
[20:19:03] [INFO] Loaded 6 PhoneThemeExcels.
[20:19:03] [INFO] Loaded 4 RelicExpItemExcels.
[20:19:03] [INFO] Loaded 38 RogueAreaExcels.
[20:19:03] [INFO] Loading floor infos... this may take a while.
[20:19:04] [INFO] Loaded 330 floor infos.
[20:19:04] [INFO] Loaded 54 maze abilities for avatars.
[20:19:04] [INFO] Loaded 74 rogue events.
[20:19:04] [INFO] Resource loading complete
[20:19:06] [INFO] Started local MongoDB server at mongodb://127.0.0.1:27017
[20:19:07] [INFO] Http Server running as: DISPATCH, GATESERVER
[20:19:07] [INFO] Http Server started on 19991
[20:19:08] [INFO] Game Server registered 136 packet handlers
[20:19:08] [INFO] Game Server started on 23301
[20:19:08] [WARN] LUNARCORE IS A FREE SOFTWARE. IF YOU PAID FOR IT, YOU HAVE BEEN SCAMMED!
[20:19:52] [INFO] Client request: query_dispatch
[20:19:55] [INFO] Client request: query_dispatch
[20:19:56] [INFO] Client request: query_dispatch
[20:20:02] [INFO] Client request: query_dispatch
> 
```

其中没有任何报错

以下是我的 `config.json` 内容：

```json
{
  "accountDatabase": {
    "uri": "mongodb://localhost:27017",
    "collection": "lunarcore",
    "useInternal": true
  },
  "gameDatabase": {
    "uri": "mongodb://localhost:27017",
    "collection": "lunarcore",
    "useInternal": true
  },
  "internalMongoServer": {
    "address": "localhost",
    "port": 27017,
    "filePath": "database.mv"
  },
  "useSameDatabase": true,
  "keystore": {
    "path": "./keystore.p12",
    "password": "lunar"
  },
  "httpServer": {
    "useSSL": false,
    "regionListRefresh": 60000,
    "bindAddress": "0.0.0.0",
    "bindPort": 19991,
    "publicAddress": "127.0.0.1",
    "publicPort": null
  },
  "gameServer": {
    "id": "lunar_rail_test",
    "name": "Lunar Core",
    "description": "A LunarCore server",
    "kcpInterval": 40,
    "kcpTimeout": 30,
    "bindAddress": "0.0.0.0",
    "bindPort": 23301,
    "publicAddress": "127.0.0.1",
    "publicPort": null
  },
  "serverOptions": {
    "autoCreateAccount": true,
    "sceneMaxEntites": 500,
    "maxCustomRelicLevel": 15,
    "unlockAllChallenges": true,
    "spendStamina": true,
    "staminaRecoveryRate": 300,
    "staminaReserveRecoveryRate": 1080,
    "startTrailblazerLevel": 1,
    "autoUpgradeWorldLevel": true,
    "language": "EN",
    "defaultPermissions": [
      "*"
    ],
    "serverFriendInfo": {
      "name": "Server",
      "signature": "Type /help for a list of commands",
      "level": 70,
      "headIcon": 202016,
      "chatBubbleId": 0,
      "displayAvatarId": 1003,
      "displayAvatarLevel": 80
    },
    "welcomeMail": {
      "title": "Welcome to a LunarCore server",
      "sender": "Server",
      "content": "Welcome to Lunar Core! Please take these items as a starter gift. For a list of commands, type /help in the server chat window. Check out our \u003ca type\u003dOpenURL1 href\u003dhttps://discord.gg/cfPKJ6N5hw\u003eDiscord\u003c/a\u003e and \u003ca type\u003dOpenURL1 href\u003dhttps://github.com/Melledy/LunarCore\u003eGithub\u003c/a\u003e for more information about the server.",
      "attachments": [
        {
          "id": 2,
          "count": 1000000
        },
        {
          "id": 101,
          "count": 100
        },
        {
          "id": 102,
          "count": 100
        },
        {
          "id": 1001,
          "count": 1
        },
        {
          "id": 1002,
          "count": 1
        }
      ]
    }
  },
  "serverTime": {
    "spoofTime": false,
    "spoofDate": "15-01-2024 08:00:00"
  },
  "serverRates": {
    "exp": 1.0,
    "credit": 1.0,
    "jade": 1.0,
    "material": 1.0,
    "equip": 1.0
  },
  "logOptions": {
    "commands": true,
    "connections": true,
    "packets": false,
    "filterLoopingPackets": false
  },
  "downloadData": {
    "assetBundleUrl": null,
    "exResourceUrl": null,
    "luaUrl": null,
    "ifixUrl": null
  },
  "resourceDir": "./resources",
  "dataDir": "./data"
}
```

请各位大佬帮忙解惑
谢谢！

**Comment by xuiogg** [comment]
httpServer.publicAddress
gameServer.publicAddress

**Comment by QSlotus** [comment]
感谢，问题已解决。
解决方法：
将这两处的ip地址改为服务器的公网ip地址即可：
`httpServer.publicAddress`
`gameServer.publicAddress`

**Comment by Wangji5673** [comment]
gameserver是用tcp端口映射还是udp

**Comment by AR-26710-sr** [comment]
找的是官网的公网ip吗 我这边试了官网的还是不管用 而且改了config.json之后运行发现代理中的代理服务器地址还是原来的

**Comment by AR-26710-sr** [comment]
> 找的是官网的公网ip吗 我这边试了官网的还是不管用 而且改了config.json之后运行发现代理中的代理服务器地址还是原来的

修改后的config.json
`{
  "accountDatabase": {
    "uri": "mongodb://localhost:27017",
    "collection": "lunarcore",
    "useInternal": true
  },
  "gameDatabase": {
    "uri": "mongodb://localhost:27017",
    "collection": "lunarcore",
    "useInternal": true
  },
  "internalMongoServer": {
    "address": "localhost",
    "port": 27017,
    "filePath": "database.mv"
  },
  "useSameDatabase": true,
  "keystore": {
    "path": "./keystore.p12",
    "password": "lunar"
  },
  "httpServer": {
    "useSSL": true,
    "regionListRefresh": 60000,
    "bindAddress": "0.0.0.0",
    "bindPort": 520,
    "publicAddress": "101.89.125.244",
    "publicPort": null
  },
  "gameServer": {
    "id": "lunar_rail_test",
    "name": "Lunar Core",
    "description": "A LunarCore server",
    "kcpInterval": 40,
    "kcpTimeout": 30,
    "bindAddress": "0.0.0.0",
    "bindPort": 23301,
    "publicAddress": "101.89.125.244",
    "publicPort": null
  },
  "serverOptions": {
    "autoCreateAccount": true,
    "sceneMaxEntites": 500,
    "maxCustomRelicLevel": 15,
    "unlockAllChallenges": true,
    "spendStamina": true,
    "staminaRecoveryRate": 300,
    "staminaReserveRecoveryRate": 1080,
    "startTrailblazerLevel": 1,
    "autoUpgradeWorldLevel": true,
    "language": "CHS",
    "defaultPermissions": [
      "*"
    ],
    "serverFriendInfo": {
      "name": "控制台",
      "signature": "输入/help获取命令列表",
      "level": 1,
      "headIcon": 201303,
      "chatBubbleId": 0,
      "displayAvatarId": 1310,
      "displayAvatarLevel": 1
    },
    "welcomeMail": {
      "title": "欢迎使用 Lunar Core",
      "sender": "Cyt",
      "content": "欢迎来到 Lunar Core! 要查看命令列表，请在服务器聊天窗口中键入/help。 建议加入 \u003ca type\u003dOpenURL1 href\u003dhttp://qm.qq.com/cgi-bin/qm/qr?_wv\u003d1027\u0026k\u003dGccs8LhDQV-H87N0YrPsTQ0-hgtJWeYc\u0026authKey\u003dZ2BsagclLE09y9ed64iQ%2BnYtvC4DojE3DLN0mrekWveVub8%2BJwU9J3fLpgpFPFBX\u0026noverify\u003d0\u0026group_code\u003d819551320\u003eQQ群\u003c/a\u003e\n 原项目地址: \u003ca type\u003dOpenURL1 href\u003dhttps://github.com/Melledy/LunarCore\u003eGithub\u003c/a\u003e",
      "attachments": [
        {
          "id": 2,
          "count": 1000000
        },
        {
          "id": 101,
          "count": 100
        },
        {
          "id": 102,
          "count": 100
        },
        {
          "id": 1001,
          "count": 1
        },
        {
          "id": 1002,
          "count": 1
        }
      ]
    }
  },
  "serverTime": {
    "spoofTime": false,
    "spoofDate": "15-01-2024 08:00:00"
  },
  "serverRates": {
    "exp": 1.0,
    "credit": 1.0,
    "jade": 1.0,
    "material": 1.0,
    "equip": 1.0
  },
  "logOptions": {
    "commands": true,
    "connections": true,
    "packets": false,
    "filterLoopingPackets": false
  },
  "resourceDir": "./resources",
  "dataDir": "./data"
}`

**Comment by AR-26710-sr** [comment]
{
  "accountDatabase": {
    "uri": "mongodb://localhost:27017",
    "collection": "lunarcore",
    "useInternal": true
  },
  "gameDatabase": {
    "uri": "mongodb://localhost:27017",
    "collection": "lunarcore",
    "useInternal": true
  },
  "internalMongoServer": {
    "address": "localhost",
    "port": 27017,
    "filePath": "database.mv"
  },
  "useSameDatabase": true,
  "keystore": {
    "path": "./keystore.p12",
    "password": "lunar"
  },
  "httpServer": {
    "useSSL": true,
    "regionListRefresh": 60000,
    "bindAddress": "0.0.0.0",
    "bindPort": 520,
    "publicAddress": "101.89.125.244",
    "publicPort": null
  },
  "gameServer": {
    "id": "lunar_rail_test",
    "name": "Lunar Core",
    "description": "A LunarCore server",
    "kcpInterval": 40,
    "kcpTimeout": 30,
    "bindAddress": "0.0.0.0",
    "bindPort": 23301,
    "publicAddress": "101.89.125.244",
    "publicPort": null
  },
  "serverOptions": {
    "autoCreateAccount": true,
    "sceneMaxEntites": 500,
    "maxCustomRelicLevel": 15,
    "unlockAllChallenges": true,
    "spendStamina": true,
    "staminaRecoveryRate": 300,
    "staminaReserveRecoveryRate": 1080,
    "startTrailblazerLevel": 1,
    "autoUpgradeWorldLevel": true,
    "language": "CHS",
    "defaultPermissions": [
      "*"
    ],
    "serverFriendInfo": {
      "name": "控制台",
      "signature": "输入/help获取命令列表",
      "level": 1,
      "headIcon": 201303,
      "chatBubbleId": 0,
      "displayAvatarId": 1310,
      "displayAvatarLevel": 1
    },
    "welcomeMail": {
      "title": "欢迎使用 Lunar Core",
      "sender": "Cyt",
      "content": "欢迎来到 Lunar Core! 要查看命令列表，请在服务器聊天窗口中键入/help。 建议加入 \u003ca type\u003dOpenURL1 href\u003dhttp://qm.qq.com/cgi-bin/qm/qr?_wv\u003d1027\u0026k\u003dGccs8LhDQV-H87N0YrPsTQ0-hgtJWeYc\u0026authKey\u003dZ2BsagclLE09y9ed64iQ%2BnYtvC4DojE3DLN0mrekWveVub8%2BJwU9J3fLpgpFPFBX\u0026noverify\u003d0\u0026group_code\u003d819551320\u003eQQ群\u003c/a\u003e\n 原项目地址: \u003ca type\u003dOpenURL1 href\u003dhttps://github.com/Melledy/LunarCore\u003eGithub\u003c/a\u003e",
      "attachments": [
        {
          "id": 2,
          "count": 1000000
        },
        {
          "id": 101,
          "count": 100
        },
        {
          "id": 102,
          "count": 100
        },
        {
          "id": 1001,
          "count": 1
        },
        {
          "id": 1002,
          "count": 1
        }
      ]
    }
  },
  "serverTime": {
    "spoofTime": false,
    "spoofDate": "15-01-2024 08:00:00"
  },
  "serverRates": {
    "exp": 1.0,
    "credit": 1.0,
    "jade": 1.0,
    "material": 1.0,
    "equip": 1.0
  },
  "logOptions": {
    "commands": true,
    "connections": true,
    "packets": false,
    "filterLoopingPackets": false
  },
  "resourceDir": "./resources",
  "dataDir": "./data"
}

**Comment by AR-26710-sr** [comment]
在sr官网找的公网ip地址中任意选了一个替换
这是修改后的github
{
  "accountDatabase": {
    "uri": "mongodb://localhost:27017",
    "collection": "lunarcore",
    "useInternal": true
  },
  "gameDatabase": {
    "uri": "mongodb://localhost:27017",
    "collection": "lunarcore",
    "useInternal": true
  },
  "internalMongoServer": {
    "address": "localhost",
    "port": 27017,
    "filePath": "database.mv"
  },
  "useSameDatabase": true,
  "keystore": {
    "path": "./keystore.p12",
    "password": "lunar"
  },
  "httpServer": {
    "useSSL": true,
    "regionListRefresh": 60000,
    "bindAddress": "0.0.0.0",
    "bindPort": 520,
    "publicAddress": "101.89.125.244",
    "publicPort": null
  },
  "gameServer": {
    "id": "lunar_rail_test",
    "name": "Lunar Core",
    "description": "A LunarCore server",
    "kcpInterval": 40,
    "kcpTimeout": 30,
    "bindAddress": "0.0.0.0",
    "bindPort": 23301,
    "publicAddress": "101.89.125.244",
    "publicPort": null
  },
  "serverOptions": {
    "autoCreateAccount": true,
    "sceneMaxEntites": 500,
    "maxCustomRelicLevel": 15,
    "unlockAllChallenges": true,
    "spendStamina": true,
    "staminaRecoveryRate": 300,
    "staminaReserveRecoveryRate": 1080,
    "startTrailblazerLevel": 1,
    "autoUpgradeWorldLevel": true,
    "language": "CHS",
    "defaultPermissions": [
      "*"
    ],
    "serverFriendInfo": {
      "name": "控制台",
      "signature": "输入/help获取命令列表",
      "level": 1,
      "headIcon": 201303,
      "chatBubbleId": 0,
      "displayAvatarId": 1310,
      "displayAvatarLevel": 1
    },
    "welcomeMail": {
      "title": "欢迎使用 Lunar Core",
      "sender": "Cyt",
      "content": "欢迎来到 Lunar Core! 要查看命令列表，请在服务器聊天窗口中键入/help。 建议加入 \u003ca type\u003dOpenURL1 href\u003dhttp://qm.qq.com/cgi-bin/qm/qr?_wv\u003d1027\u0026k\u003dGccs8LhDQV-H87N0YrPsTQ0-hgtJWeYc\u0026authKey\u003dZ2BsagclLE09y9ed64iQ%2BnYtvC4DojE3DLN0mrekWveVub8%2BJwU9J3fLpgpFPFBX\u0026noverify\u003d0\u0026group_code\u003d819551320\u003eQQ群\u003c/a\u003e\n 原项目地址: \u003ca type\u003dOpenURL1 href\u003dhttps://github.com/Melledy/LunarCore\u003eGithub\u003c/a\u003e",
      "attachments": [
        {
          "id": 2,
          "count": 1000000
        },
        {
          "id": 101,
          "count": 100
        },
        {
          "id": 102,
          "count": 100
        },
        {
          "id": 1001,
          "count": 1
        },
        {
          "id": 1002,
          "count": 1
        }
      ]
    }
  },
  "serverTime": {
    "spoofTime": false,
    "spoofDate": "15-01-2024 08:00:00"
  },
  "serverRates": {
    "exp": 1.0,
    "credit": 1.0,
    "jade": 1.0,
    "material": 1.0,
    "equip": 1.0
  },
  "logOptions": {
    "commands": true,
    "connections": true,
    "packets": false,
    "filterLoopingPackets": false
  },
  "resourceDir": "./resources",
  "dataDir": "./data"
}

**Comment by AR-26710-sr** [comment]
用的是2.3私服

**Comment by QSlotus** [comment]
> 找的是官网的公网ip吗 我这边试了官网的还是不管用 而且改了config.json之后运行发现代理中的代理服务器地址还是原来的

如果你的服务端部署在你的本地那么配置无需更改
如果你的服务端被部署在了远程服务器上，那么`httpServer.publicAddress` `gameServer.publicAddress` 这两处的配置需更改为 **你远程服务器的公网ip地址** 而非 HSR 官网的ip地址
