### ISSUE TITLE
LunarCore登录时需要通过验证

### ISSUE THREAD

**Issue by redball1017** [Melledy/LunarCore#92]
游戏版本:2.4.0
平台:Android 14
详细描述：官方服务器登录时不会出现验证问题。但是一旦连接到自搭建LunarCore的服务器后，一登录账号就显示验证中，不一会就会出现验证窗口，显示网络不给力
视频演示:

https://github.com/user-attachments/assets/aa541dcc-8f56-40a0-a77f-24770c1f0ebe

**Comment by Xuoos** [comment]
把模块禁用ab测试打开

**Comment by redball1017** [comment]
> 把模块禁用ab测试打开

谢了，不过我发现只有国服会出现这种情况，如果用国际服的星铁是可以正常登录游玩的
